services:
  greenlight_api:
    image: ghcr.io/greenlightquiz/backend:latest
    container_name: greenlight_api
    restart: unless-stopped
    environment:
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env.docker
    ports:
      - "127.0.0.1:8000:8000"
    deploy:
      resources:
        limits:
          memory: 200M
